### ISSUE TITLE
请问行号会有黑色突出显示，这个如何设置？

### ISSUE THREAD

**Issue by mikaizhu** [nickdevhouse/dotfiles#1]

**Comment by nickdevhouse** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/126865781/232206286-a7e00a98-fbff-416b-bce3-e94f4e419618.png">

可以在图里面高亮的位置修改你需要的颜色。

甚至如果你想修改其他的highlight配置，可以直接在neovim里面输入“:hightlight”，即可显示目前所有的高亮配置（同样可以在neosolarized.lua里修改）。

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/126865781/232206433-a06f505b-940e-4d2e-88c7-89ebd9b661a4.png">
